// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ssh$0 from "../ssh/models.js";

export function CancelTransfer(taskID: string): $CancellablePromise<void> {
    return $Call.ByName("mssh/internal/service.FileService.CancelTransfer", taskID);
}

export function Delete(sessionID: number, path: string): $CancellablePromise<void> {
    return $Call.ByName("mssh/internal/service.FileService.Delete", sessionID, path);
}

export function Download(sessionID: number, remotePath: string, localPath: string): $CancellablePromise<string> {
    return $Call.ByName("mssh/internal/service.FileService.Download", sessionID, remotePath, localPath);
}

export function ListDir(sessionID: number, path: string): $CancellablePromise<ssh$0.FileEntry[]> {
    return $Call.ByName("mssh/internal/service.FileService.ListDir", sessionID, path).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Mkdir(sessionID: number, path: string): $CancellablePromise<void> {
    return $Call.ByName("mssh/internal/service.FileService.Mkdir", sessionID, path);
}

export function Rename(sessionID: number, oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByName("mssh/internal/service.FileService.Rename", sessionID, oldPath, newPath);
}

export function Upload(sessionID: number, localPath: string, remotePath: string): $CancellablePromise<string> {
    return $Call.ByName("mssh/internal/service.FileService.Upload", sessionID, localPath, remotePath);
}

// Private type creation functions
const $$createType0 = ssh$0.FileEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
