// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Export(path: string): $CancellablePromise<void> {
    return $Call.ByName("mssh/internal/service.SyncService.Export", path);
}

export function Import(path: string): $CancellablePromise<void> {
    return $Call.ByName("mssh/internal/service.SyncService.Import", path);
}

export function SyncFromCloud(): $CancellablePromise<void> {
    return $Call.ByName("mssh/internal/service.SyncService.SyncFromCloud");
}

export function SyncToCloud(): $CancellablePromise<void> {
    return $Call.ByName("mssh/internal/service.SyncService.SyncToCloud");
}
