// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AboutInfo {
    "current_version": string;
    "repository_url": string;

    /** Creates a new AboutInfo instance. */
    constructor($$source: Partial<AboutInfo> = {}) {
        if (!("current_version" in $$source)) {
            this["current_version"] = "";
        }
        if (!("repository_url" in $$source)) {
            this["repository_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AboutInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AboutInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AboutInfo($$parsedSource as Partial<AboutInfo>);
    }
}

export enum AuthMethod {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthPassword = "password",
    AuthKey = "key",
    AuthAgent = "agent",
    AuthKeyboardInteractive = "keyboard-interactive",
};

export class BuiltinThemeResetResult {
    "dark_reset": boolean;
    "light_reset": boolean;
    "fixed_reset": boolean;

    /** Creates a new BuiltinThemeResetResult instance. */
    constructor($$source: Partial<BuiltinThemeResetResult> = {}) {
        if (!("dark_reset" in $$source)) {
            this["dark_reset"] = false;
        }
        if (!("light_reset" in $$source)) {
            this["light_reset"] = false;
        }
        if (!("fixed_reset" in $$source)) {
            this["fixed_reset"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuiltinThemeResetResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BuiltinThemeResetResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BuiltinThemeResetResult($$parsedSource as Partial<BuiltinThemeResetResult>);
    }
}

export enum CursorStyle {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CursorStyleBlock = "block",
    CursorStyleUnderline = "underline",
    CursorStyleBar = "bar",
};

export enum KeyType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KeyTypeRSA = "rsa",
    KeyTypeED25519 = "ed25519",
    KeyTypeECDSA = "ecdsa",
};

export class Macro {
    "id": number;
    "name": string;
    "command": string;
    "shortcut": string;
    "delay_ms": number;
    "sort_order": number;
    "created_at": string;

    /** Creates a new Macro instance. */
    constructor($$source: Partial<Macro> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("shortcut" in $$source)) {
            this["shortcut"] = "";
        }
        if (!("delay_ms" in $$source)) {
            this["delay_ms"] = 0;
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Macro instance from a string or object.
     */
    static createFrom($$source: any = {}): Macro {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Macro($$parsedSource as Partial<Macro>);
    }
}

export class MacroInput {
    "id": number;
    "name": string;
    "command": string;
    "shortcut": string;
    "delay_ms": number;
    "sort_order": number;

    /** Creates a new MacroInput instance. */
    constructor($$source: Partial<MacroInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("shortcut" in $$source)) {
            this["shortcut"] = "";
        }
        if (!("delay_ms" in $$source)) {
            this["delay_ms"] = 0;
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MacroInput instance from a string or object.
     */
    static createFrom($$source: any = {}): MacroInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MacroInput($$parsedSource as Partial<MacroInput>);
    }
}

export enum RecordType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    RecordStdout = 0,
    RecordStdin = 1,
};

export class RecordingEntry {
    "timestamp": number;
    "type": RecordType;
    "data": string;

    /** Creates a new RecordingEntry instance. */
    constructor($$source: Partial<RecordingEntry> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }
        if (!("type" in $$source)) {
            this["type"] = RecordType.$zero;
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordingEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordingEntry {
        const $$createField2_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new RecordingEntry($$parsedSource as Partial<RecordingEntry>);
    }
}

export class SSHKey {
    "id": number;
    "name": string;
    "type": KeyType;
    "public_key": string;
    "has_passphrase": boolean;
    "created_at": string;

    /** Creates a new SSHKey instance. */
    constructor($$source: Partial<SSHKey> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = KeyType.$zero;
        }
        if (!("public_key" in $$source)) {
            this["public_key"] = "";
        }
        if (!("has_passphrase" in $$source)) {
            this["has_passphrase"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHKey instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHKey {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHKey($$parsedSource as Partial<SSHKey>);
    }
}

export class SSHKeyImportFile {
    "name": string;
    "private_key": string;

    /** Creates a new SSHKeyImportFile instance. */
    constructor($$source: Partial<SSHKeyImportFile> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("private_key" in $$source)) {
            this["private_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHKeyImportFile instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHKeyImportFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHKeyImportFile($$parsedSource as Partial<SSHKeyImportFile>);
    }
}

export class SSHKeyMaterial {
    "id": number;
    "name": string;
    "type": KeyType;
    "private_key": string;
    "public_key": string;
    "created_at": string;

    /** Creates a new SSHKeyMaterial instance. */
    constructor($$source: Partial<SSHKeyMaterial> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = KeyType.$zero;
        }
        if (!("private_key" in $$source)) {
            this["private_key"] = "";
        }
        if (!("public_key" in $$source)) {
            this["public_key"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHKeyMaterial instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHKeyMaterial {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHKeyMaterial($$parsedSource as Partial<SSHKeyMaterial>);
    }
}

export class SSHKeyUpdateInput {
    "id": number;
    "name": string;
    "private_key": string;
    "public_key": string;

    /** Creates a new SSHKeyUpdateInput instance. */
    constructor($$source: Partial<SSHKeyUpdateInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("private_key" in $$source)) {
            this["private_key"] = "";
        }
        if (!("public_key" in $$source)) {
            this["public_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHKeyUpdateInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHKeyUpdateInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHKeyUpdateInput($$parsedSource as Partial<SSHKeyUpdateInput>);
    }
}

export class Session {
    "id": number;
    "folder_id": number | null;
    "name": string;
    "host": string;
    "port": number;
    "username": string;
    "tags": string;
    "notes": string;
    "environment": string;
    "project": string;
    "auth_method": AuthMethod;
    "password"?: string;
    "key_id"?: number | null;
    "keep_alive": number;
    "term_type": string;
    "sort_order": number;
    "last_connected_at"?: string | null;
    "connection_count": number;
    "created_at": string;
    "updated_at": string;

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("folder_id" in $$source)) {
            this["folder_id"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("tags" in $$source)) this["tags"] = "";
        if (!("notes" in $$source)) this["notes"] = "";
        if (!("environment" in $$source)) this["environment"] = "";
        if (!("project" in $$source)) this["project"] = "";
        if (!("auth_method" in $$source)) {
            this["auth_method"] = AuthMethod.$zero;
        }
        if (!("keep_alive" in $$source)) {
            this["keep_alive"] = 0;
        }
        if (!("term_type" in $$source)) {
            this["term_type"] = "";
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }
        if (!("connection_count" in $$source)) {
            this["connection_count"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Session($$parsedSource as Partial<Session>);
    }
}

export class SessionFolder {
    "id": number;
    "name": string;
    "parent_id": number | null;
    "is_default": boolean;
    "sort_order": number;
    "created_at": string;
    "updated_at": string;

    /** Creates a new SessionFolder instance. */
    constructor($$source: Partial<SessionFolder> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("parent_id" in $$source)) {
            this["parent_id"] = null;
        }
        if (!("is_default" in $$source)) {
            this["is_default"] = false;
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionFolder instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionFolder {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionFolder($$parsedSource as Partial<SessionFolder>);
    }
}

export class SessionInput {
    "id": number;
    "folder_id": number | null;
    "name": string;
    "host": string;
    "port": number;
    "username": string;
    "tags": string;
    "notes": string;
    "environment": string;
    "project": string;
    "auth_method": AuthMethod;
    "password"?: string;
    "key_id"?: number | null;
    "keep_alive": number;
    "term_type": string;
    "sort_order": number;

    /** Creates a new SessionInput instance. */
    constructor($$source: Partial<SessionInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("folder_id" in $$source)) {
            this["folder_id"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("tags" in $$source)) this["tags"] = "";
        if (!("notes" in $$source)) this["notes"] = "";
        if (!("environment" in $$source)) this["environment"] = "";
        if (!("project" in $$source)) this["project"] = "";
        if (!("auth_method" in $$source)) {
            this["auth_method"] = AuthMethod.$zero;
        }
        if (!("keep_alive" in $$source)) {
            this["keep_alive"] = 0;
        }
        if (!("term_type" in $$source)) {
            this["term_type"] = "";
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionInput($$parsedSource as Partial<SessionInput>);
    }
}

export class SessionLog {
    "id": number;
    "session_id": number | null;
    "started_at": string;
    "ended_at"?: string | null;
    "data_path": string;

    /** Creates a new SessionLog instance. */
    constructor($$source: Partial<SessionLog> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = null;
        }
        if (!("started_at" in $$source)) {
            this["started_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("data_path" in $$source)) {
            this["data_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionLog instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionLog {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionLog($$parsedSource as Partial<SessionLog>);
    }
}

export class Setting {
    "key": string;
    "namespace": string;
    "value": string;
    "value_type": string;
    "version": number;
    "updated_at": string;

    /** Creates a new Setting instance. */
    constructor($$source: Partial<Setting> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("value_type" in $$source)) {
            this["value_type"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Setting instance from a string or object.
     */
    static createFrom($$source: any = {}): Setting {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Setting($$parsedSource as Partial<Setting>);
    }
}

export class SettingInput {
    "key": string;
    "namespace": string;
    "value": string;
    "value_type": string;
    "version": number;

    /** Creates a new SettingInput instance. */
    constructor($$source: Partial<SettingInput> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("value_type" in $$source)) {
            this["value_type"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingInput($$parsedSource as Partial<SettingInput>);
    }
}

export class TerminalGlobalStyle {
    "font_family": string;
    "font_size": number;
    "cursor_style": CursorStyle;
    "selection_background": string;

    /** Creates a new TerminalGlobalStyle instance. */
    constructor($$source: Partial<TerminalGlobalStyle> = {}) {
        if (!("font_family" in $$source)) {
            this["font_family"] = "";
        }
        if (!("font_size" in $$source)) {
            this["font_size"] = 0;
        }
        if (!("cursor_style" in $$source)) {
            this["cursor_style"] = CursorStyle.$zero;
        }
        if (!("selection_background" in $$source)) {
            this["selection_background"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalGlobalStyle instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalGlobalStyle {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalGlobalStyle($$parsedSource as Partial<TerminalGlobalStyle>);
    }
}

export class TerminalGlobalStyleInput {
    "font_family": string;
    "font_size": number;
    "cursor_style": CursorStyle;
    "selection_background": string;

    /** Creates a new TerminalGlobalStyleInput instance. */
    constructor($$source: Partial<TerminalGlobalStyleInput> = {}) {
        if (!("font_family" in $$source)) {
            this["font_family"] = "";
        }
        if (!("font_size" in $$source)) {
            this["font_size"] = 0;
        }
        if (!("cursor_style" in $$source)) {
            this["cursor_style"] = CursorStyle.$zero;
        }
        if (!("selection_background" in $$source)) {
            this["selection_background"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalGlobalStyleInput instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalGlobalStyleInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalGlobalStyleInput($$parsedSource as Partial<TerminalGlobalStyleInput>);
    }
}

export class ThemeAssignments {
    "dark_profile_id": number;
    "light_profile_id": number;
    "follow_interface_mode": boolean;
    "fixed_profile_id": number;

    /** Creates a new ThemeAssignments instance. */
    constructor($$source: Partial<ThemeAssignments> = {}) {
        if (!("dark_profile_id" in $$source)) {
            this["dark_profile_id"] = 0;
        }
        if (!("light_profile_id" in $$source)) {
            this["light_profile_id"] = 0;
        }
        if (!("follow_interface_mode" in $$source)) {
            this["follow_interface_mode"] = false;
        }
        if (!("fixed_profile_id" in $$source)) {
            this["fixed_profile_id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeAssignments instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeAssignments {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeAssignments($$parsedSource as Partial<ThemeAssignments>);
    }
}

export class ThemeAssignmentsInput {
    "dark_profile_id": number;
    "light_profile_id": number;
    "follow_interface_mode": boolean;
    "fixed_profile_id": number;

    /** Creates a new ThemeAssignmentsInput instance. */
    constructor($$source: Partial<ThemeAssignmentsInput> = {}) {
        if (!("dark_profile_id" in $$source)) {
            this["dark_profile_id"] = 0;
        }
        if (!("light_profile_id" in $$source)) {
            this["light_profile_id"] = 0;
        }
        if (!("follow_interface_mode" in $$source)) {
            this["follow_interface_mode"] = false;
        }
        if (!("fixed_profile_id" in $$source)) {
            this["fixed_profile_id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeAssignmentsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeAssignmentsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeAssignmentsInput($$parsedSource as Partial<ThemeAssignmentsInput>);
    }
}

export class ThemeConfigurationInput {
    "global_style": TerminalGlobalStyleInput;
    "profiles": ThemeProfileInput[];
    "assignments": ThemeAssignmentsInput;

    /** Creates a new ThemeConfigurationInput instance. */
    constructor($$source: Partial<ThemeConfigurationInput> = {}) {
        if (!("global_style" in $$source)) {
            this["global_style"] = (new TerminalGlobalStyleInput());
        }
        if (!("profiles" in $$source)) {
            this["profiles"] = [];
        }
        if (!("assignments" in $$source)) {
            this["assignments"] = (new ThemeAssignmentsInput());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeConfigurationInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeConfigurationInput {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("global_style" in $$parsedSource) {
            $$parsedSource["global_style"] = $$createField0_0($$parsedSource["global_style"]);
        }
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField1_0($$parsedSource["profiles"]);
        }
        if ("assignments" in $$parsedSource) {
            $$parsedSource["assignments"] = $$createField2_0($$parsedSource["assignments"]);
        }
        return new ThemeConfigurationInput($$parsedSource as Partial<ThemeConfigurationInput>);
    }
}

export class ThemeDefinition {
    "id": number;
    "name": string;
    "mode": ThemeMode;
    "source_type": ThemeSourceType;
    "source_name": string;
    "source_url": string;
    "source_author": string;
    "source_license": string;
    "source_version": string;
    "source_fingerprint": string;
    "color_payload": string;
    "raw_payload": string;
    "is_builtin": boolean;
    "created_at": string;
    "updated_at": string;

    /** Creates a new ThemeDefinition instance. */
    constructor($$source: Partial<ThemeDefinition> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = ThemeMode.$zero;
        }
        if (!("source_type" in $$source)) {
            this["source_type"] = ThemeSourceType.$zero;
        }
        if (!("source_name" in $$source)) {
            this["source_name"] = "";
        }
        if (!("source_url" in $$source)) {
            this["source_url"] = "";
        }
        if (!("source_author" in $$source)) {
            this["source_author"] = "";
        }
        if (!("source_license" in $$source)) {
            this["source_license"] = "";
        }
        if (!("source_version" in $$source)) {
            this["source_version"] = "";
        }
        if (!("source_fingerprint" in $$source)) {
            this["source_fingerprint"] = "";
        }
        if (!("color_payload" in $$source)) {
            this["color_payload"] = "";
        }
        if (!("raw_payload" in $$source)) {
            this["raw_payload"] = "";
        }
        if (!("is_builtin" in $$source)) {
            this["is_builtin"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeDefinition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeDefinition($$parsedSource as Partial<ThemeDefinition>);
    }
}

export class ThemeImportResult {
    "file": string;
    "name": string;
    "status": ThemeImportStatus;
    "definition_id": number;
    "profile_id": number;
    "error": string;

    /** Creates a new ThemeImportResult instance. */
    constructor($$source: Partial<ThemeImportResult> = {}) {
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = ThemeImportStatus.$zero;
        }
        if (!("definition_id" in $$source)) {
            this["definition_id"] = 0;
        }
        if (!("profile_id" in $$source)) {
            this["profile_id"] = 0;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeImportResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeImportResult($$parsedSource as Partial<ThemeImportResult>);
    }
}

export enum ThemeImportStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ThemeImportImported = "imported",
    ThemeImportDuplicate = "duplicate",
    ThemeImportFailed = "failed",
};

export class ThemeImportSummary {
    "results": ThemeImportResult[];

    /** Creates a new ThemeImportSummary instance. */
    constructor($$source: Partial<ThemeImportSummary> = {}) {
        if (!("results" in $$source)) {
            this["results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeImportSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeImportSummary {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        return new ThemeImportSummary($$parsedSource as Partial<ThemeImportSummary>);
    }
}

export enum ThemeMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ThemeModeDark = "dark",
    ThemeModeLight = "light",
    ThemeModeUniversal = "universal",
};

export class ThemeProfile {
    "id": number;
    "name": string;
    "theme_id": number;
    "definition"?: ThemeDefinition | null;
    "follow_global_style": boolean;
    "font_family": string;
    "font_size": number;
    "cursor_style": CursorStyle;
    "color_overrides": string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new ThemeProfile instance. */
    constructor($$source: Partial<ThemeProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("theme_id" in $$source)) {
            this["theme_id"] = 0;
        }
        if (!("follow_global_style" in $$source)) {
            this["follow_global_style"] = false;
        }
        if (!("font_family" in $$source)) {
            this["font_family"] = "";
        }
        if (!("font_size" in $$source)) {
            this["font_size"] = 0;
        }
        if (!("cursor_style" in $$source)) {
            this["cursor_style"] = CursorStyle.$zero;
        }
        if (!("color_overrides" in $$source)) {
            this["color_overrides"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeProfile {
        const $$createField3_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("definition" in $$parsedSource) {
            $$parsedSource["definition"] = $$createField3_0($$parsedSource["definition"]);
        }
        return new ThemeProfile($$parsedSource as Partial<ThemeProfile>);
    }
}

export class ThemeProfileInput {
    "id": number;
    "name": string;
    "theme_id": number;
    "follow_global_style": boolean;
    "font_family": string;
    "font_size": number;
    "cursor_style": CursorStyle;
    "color_overrides": string;

    /** Creates a new ThemeProfileInput instance. */
    constructor($$source: Partial<ThemeProfileInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("theme_id" in $$source)) {
            this["theme_id"] = 0;
        }
        if (!("follow_global_style" in $$source)) {
            this["follow_global_style"] = false;
        }
        if (!("font_family" in $$source)) {
            this["font_family"] = "";
        }
        if (!("font_size" in $$source)) {
            this["font_size"] = 0;
        }
        if (!("cursor_style" in $$source)) {
            this["cursor_style"] = CursorStyle.$zero;
        }
        if (!("color_overrides" in $$source)) {
            this["color_overrides"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeProfileInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeProfileInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeProfileInput($$parsedSource as Partial<ThemeProfileInput>);
    }
}

export enum ThemeSourceType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ThemeSourceBuiltin = "builtin",
    ThemeSourceITerm2 = "iterm2",
    ThemeSourceCommunity = "community",
    ThemeSourceCustom = "custom",
};

export class Tunnel {
    "id": number;
    "session_id": number;
    "name": string;
    "type": TunnelType;
    "local_host"?: string;
    "local_port": number;
    "remote_host"?: string;
    "remote_port": number;
    "created_at": string;

    /** Creates a new Tunnel instance. */
    constructor($$source: Partial<Tunnel> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = TunnelType.$zero;
        }
        if (!("local_port" in $$source)) {
            this["local_port"] = 0;
        }
        if (!("remote_port" in $$source)) {
            this["remote_port"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tunnel instance from a string or object.
     */
    static createFrom($$source: any = {}): Tunnel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tunnel($$parsedSource as Partial<Tunnel>);
    }
}

export class TunnelInput {
    "id": number;
    "session_id": number;
    "name": string;
    "type": TunnelType;
    "local_host"?: string;
    "local_port": number;
    "remote_host"?: string;
    "remote_port": number;

    /** Creates a new TunnelInput instance. */
    constructor($$source: Partial<TunnelInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = TunnelType.$zero;
        }
        if (!("local_port" in $$source)) {
            this["local_port"] = 0;
        }
        if (!("remote_port" in $$source)) {
            this["remote_port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelInput instance from a string or object.
     */
    static createFrom($$source: any = {}): TunnelInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TunnelInput($$parsedSource as Partial<TunnelInput>);
    }
}

export enum TunnelType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TunnelLocal = "local",
    TunnelRemote = "remote",
    TunnelDynamic = "dynamic",
};

export class UpdateInfo {
    "current_version": string;
    "latest_version": string;
    "release_url": string;
    "update_available": boolean;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("current_version" in $$source)) {
            this["current_version"] = "";
        }
        if (!("latest_version" in $$source)) {
            this["latest_version"] = "";
        }
        if (!("release_url" in $$source)) {
            this["release_url"] = "";
        }
        if (!("update_available" in $$source)) {
            this["update_available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

// Private type creation functions
const $$createType0 = TerminalGlobalStyleInput.createFrom;
const $$createType1 = ThemeProfileInput.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ThemeAssignmentsInput.createFrom;
const $$createType4 = ThemeImportResult.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = ThemeDefinition.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
