// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AboutInfo {
    "current_version": string;
    "repository_url": string;

    /** Creates a new AboutInfo instance. */
    constructor($$source: Partial<AboutInfo> = {}) {
        if (!("current_version" in $$source)) {
            this["current_version"] = "";
        }
        if (!("repository_url" in $$source)) {
            this["repository_url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AboutInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): AboutInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AboutInfo($$parsedSource as Partial<AboutInfo>);
    }
}

export enum AssetColorToken {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AssetColorSlate = "slate",
    AssetColorRed = "red",
    AssetColorOrange = "orange",
    AssetColorAmber = "amber",
    AssetColorYellow = "yellow",
    AssetColorLime = "lime",
    AssetColorGreen = "green",
    AssetColorTeal = "teal",
    AssetColorCyan = "cyan",
    AssetColorBlue = "blue",
    AssetColorViolet = "violet",
    AssetColorPink = "pink",
};

export class AssetDeleteImpact {
    "id": number;
    "name": string;
    "session_count": number;

    /** Creates a new AssetDeleteImpact instance. */
    constructor($$source: Partial<AssetDeleteImpact> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("session_count" in $$source)) {
            this["session_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetDeleteImpact instance from a string or object.
     */
    static createFrom($$source: any = {}): AssetDeleteImpact {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssetDeleteImpact($$parsedSource as Partial<AssetDeleteImpact>);
    }
}

export class AssetDeleteInput {
    "id": number;
    "mode": string;
    "replacement_id": number | null;

    /** Creates a new AssetDeleteInput instance. */
    constructor($$source: Partial<AssetDeleteInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("replacement_id" in $$source)) {
            this["replacement_id"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetDeleteInput instance from a string or object.
     */
    static createFrom($$source: any = {}): AssetDeleteInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssetDeleteInput($$parsedSource as Partial<AssetDeleteInput>);
    }
}

export class AssetEnvironment {
    "id": number;
    "name": string;
    "color_token": AssetColorToken;
    "sort_order": number;
    "session_count": number;
    "created_at": string;
    "updated_at": string;

    /** Creates a new AssetEnvironment instance. */
    constructor($$source: Partial<AssetEnvironment> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("color_token" in $$source)) {
            this["color_token"] = AssetColorToken.$zero;
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }
        if (!("session_count" in $$source)) {
            this["session_count"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetEnvironment instance from a string or object.
     */
    static createFrom($$source: any = {}): AssetEnvironment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssetEnvironment($$parsedSource as Partial<AssetEnvironment>);
    }
}

export class AssetEnvironmentInput {
    "id": number;
    "name": string;
    "color_token": AssetColorToken;
    "sort_order": number;

    /** Creates a new AssetEnvironmentInput instance. */
    constructor($$source: Partial<AssetEnvironmentInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("color_token" in $$source)) {
            this["color_token"] = AssetColorToken.$zero;
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetEnvironmentInput instance from a string or object.
     */
    static createFrom($$source: any = {}): AssetEnvironmentInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssetEnvironmentInput($$parsedSource as Partial<AssetEnvironmentInput>);
    }
}

export class AssetProject {
    "id": number;
    "name": string;
    "code": string;
    "description": string;
    "sort_order": number;
    "session_count": number;
    "created_at": string;
    "updated_at": string;

    /** Creates a new AssetProject instance. */
    constructor($$source: Partial<AssetProject> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }
        if (!("session_count" in $$source)) {
            this["session_count"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetProject instance from a string or object.
     */
    static createFrom($$source: any = {}): AssetProject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssetProject($$parsedSource as Partial<AssetProject>);
    }
}

export class AssetProjectInput {
    "id": number;
    "name": string;
    "code": string;
    "description": string;
    "sort_order": number;

    /** Creates a new AssetProjectInput instance. */
    constructor($$source: Partial<AssetProjectInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetProjectInput instance from a string or object.
     */
    static createFrom($$source: any = {}): AssetProjectInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssetProjectInput($$parsedSource as Partial<AssetProjectInput>);
    }
}

export class AssetTag {
    "id": number;
    "name": string;
    "color_token": AssetColorToken;
    "session_count": number;
    "created_at": string;
    "updated_at": string;

    /** Creates a new AssetTag instance. */
    constructor($$source: Partial<AssetTag> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("color_token" in $$source)) {
            this["color_token"] = AssetColorToken.$zero;
        }
        if (!("session_count" in $$source)) {
            this["session_count"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetTag instance from a string or object.
     */
    static createFrom($$source: any = {}): AssetTag {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssetTag($$parsedSource as Partial<AssetTag>);
    }
}

export class AssetTagInput {
    "id": number;
    "name": string;
    "color_token": AssetColorToken;

    /** Creates a new AssetTagInput instance. */
    constructor($$source: Partial<AssetTagInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("color_token" in $$source)) {
            this["color_token"] = AssetColorToken.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetTagInput instance from a string or object.
     */
    static createFrom($$source: any = {}): AssetTagInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssetTagInput($$parsedSource as Partial<AssetTagInput>);
    }
}

export class AuditEvent {
    "id": number;
    "action": string;
    "target_type": string;
    "target_id": string;
    "session_id": number | null;
    "summary": string;
    "outcome": string;
    "created_at": string;

    /** Creates a new AuditEvent instance. */
    constructor($$source: Partial<AuditEvent> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("target_type" in $$source)) {
            this["target_type"] = "";
        }
        if (!("target_id" in $$source)) {
            this["target_id"] = "";
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = null;
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("outcome" in $$source)) {
            this["outcome"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuditEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): AuditEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuditEvent($$parsedSource as Partial<AuditEvent>);
    }
}

export class AuditFilter {
    "action": string;
    "session_id": number | null;
    "from": string;
    "to": string;
    "limit": number;

    /** Creates a new AuditFilter instance. */
    constructor($$source: Partial<AuditFilter> = {}) {
        if (!("action" in $$source)) {
            this["action"] = "";
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = null;
        }
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("to" in $$source)) {
            this["to"] = "";
        }
        if (!("limit" in $$source)) {
            this["limit"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AuditFilter instance from a string or object.
     */
    static createFrom($$source: any = {}): AuditFilter {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AuditFilter($$parsedSource as Partial<AuditFilter>);
    }
}

export enum AuthMethod {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthPassword = "password",
    AuthKey = "key",
    AuthAgent = "agent",
    AuthKeyboardInteractive = "keyboard-interactive",
};

export class BuiltinThemeResetResult {
    "dark_reset": boolean;
    "light_reset": boolean;
    "fixed_reset": boolean;

    /** Creates a new BuiltinThemeResetResult instance. */
    constructor($$source: Partial<BuiltinThemeResetResult> = {}) {
        if (!("dark_reset" in $$source)) {
            this["dark_reset"] = false;
        }
        if (!("light_reset" in $$source)) {
            this["light_reset"] = false;
        }
        if (!("fixed_reset" in $$source)) {
            this["fixed_reset"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuiltinThemeResetResult instance from a string or object.
     */
    static createFrom($$source: any = {}): BuiltinThemeResetResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BuiltinThemeResetResult($$parsedSource as Partial<BuiltinThemeResetResult>);
    }
}

export class BulkAssetAssignmentInput {
    "session_ids": number[];
    "target_id": number | null;

    /** Creates a new BulkAssetAssignmentInput instance. */
    constructor($$source: Partial<BulkAssetAssignmentInput> = {}) {
        if (!("session_ids" in $$source)) {
            this["session_ids"] = [];
        }
        if (!("target_id" in $$source)) {
            this["target_id"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BulkAssetAssignmentInput instance from a string or object.
     */
    static createFrom($$source: any = {}): BulkAssetAssignmentInput {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session_ids" in $$parsedSource) {
            $$parsedSource["session_ids"] = $$createField0_0($$parsedSource["session_ids"]);
        }
        return new BulkAssetAssignmentInput($$parsedSource as Partial<BulkAssetAssignmentInput>);
    }
}

export class BulkTagUpdateInput {
    "session_ids": number[];
    "tag_ids": number[];
    "operation": string;

    /** Creates a new BulkTagUpdateInput instance. */
    constructor($$source: Partial<BulkTagUpdateInput> = {}) {
        if (!("session_ids" in $$source)) {
            this["session_ids"] = [];
        }
        if (!("tag_ids" in $$source)) {
            this["tag_ids"] = [];
        }
        if (!("operation" in $$source)) {
            this["operation"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BulkTagUpdateInput instance from a string or object.
     */
    static createFrom($$source: any = {}): BulkTagUpdateInput {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("session_ids" in $$parsedSource) {
            $$parsedSource["session_ids"] = $$createField0_0($$parsedSource["session_ids"]);
        }
        if ("tag_ids" in $$parsedSource) {
            $$parsedSource["tag_ids"] = $$createField1_0($$parsedSource["tag_ids"]);
        }
        return new BulkTagUpdateInput($$parsedSource as Partial<BulkTagUpdateInput>);
    }
}

export class CommandHistory {
    "id": number;
    "session_id": number;
    "command": string;
    "created_at": string;

    /** Creates a new CommandHistory instance. */
    constructor($$source: Partial<CommandHistory> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandHistory instance from a string or object.
     */
    static createFrom($$source: any = {}): CommandHistory {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandHistory($$parsedSource as Partial<CommandHistory>);
    }
}

export enum CursorStyle {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    CursorStyleBlock = "block",
    CursorStyleUnderline = "underline",
    CursorStyleBar = "bar",
};

export class HostKeyEntry {
    "line": number;
    "hosts": string;
    "algorithm": string;
    "fingerprint": string;

    /** Creates a new HostKeyEntry instance. */
    constructor($$source: Partial<HostKeyEntry> = {}) {
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("hosts" in $$source)) {
            this["hosts"] = "";
        }
        if (!("algorithm" in $$source)) {
            this["algorithm"] = "";
        }
        if (!("fingerprint" in $$source)) {
            this["fingerprint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HostKeyEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): HostKeyEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HostKeyEntry($$parsedSource as Partial<HostKeyEntry>);
    }
}

export enum KeyType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KeyTypeRSA = "rsa",
    KeyTypeED25519 = "ed25519",
    KeyTypeECDSA = "ecdsa",
};

export class Macro {
    "id": number;
    "name": string;
    "command": string;
    "shortcut": string;
    "delay_ms": number;
    "sort_order": number;
    "created_at": string;

    /** Creates a new Macro instance. */
    constructor($$source: Partial<Macro> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("shortcut" in $$source)) {
            this["shortcut"] = "";
        }
        if (!("delay_ms" in $$source)) {
            this["delay_ms"] = 0;
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Macro instance from a string or object.
     */
    static createFrom($$source: any = {}): Macro {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Macro($$parsedSource as Partial<Macro>);
    }
}

export class MacroInput {
    "id": number;
    "name": string;
    "command": string;
    "shortcut": string;
    "delay_ms": number;
    "sort_order": number;

    /** Creates a new MacroInput instance. */
    constructor($$source: Partial<MacroInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("shortcut" in $$source)) {
            this["shortcut"] = "";
        }
        if (!("delay_ms" in $$source)) {
            this["delay_ms"] = 0;
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MacroInput instance from a string or object.
     */
    static createFrom($$source: any = {}): MacroInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MacroInput($$parsedSource as Partial<MacroInput>);
    }
}

export class NetworkInterface {
    "name": string;
    "received_bytes": number;
    "transmitted_bytes": number;
    "download_rate": number;
    "upload_rate": number;

    /** Creates a new NetworkInterface instance. */
    constructor($$source: Partial<NetworkInterface> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("received_bytes" in $$source)) {
            this["received_bytes"] = 0;
        }
        if (!("transmitted_bytes" in $$source)) {
            this["transmitted_bytes"] = 0;
        }
        if (!("download_rate" in $$source)) {
            this["download_rate"] = 0;
        }
        if (!("upload_rate" in $$source)) {
            this["upload_rate"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkInterface instance from a string or object.
     */
    static createFrom($$source: any = {}): NetworkInterface {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NetworkInterface($$parsedSource as Partial<NetworkInterface>);
    }
}

export class ProcessInfo {
    "pid": number;
    "ppid": number;
    "user": string;
    "state": string;
    "cpu_percent": number;
    "memory_bytes": number;
    "rss_bytes": number;
    "command": string;

    /** Creates a new ProcessInfo instance. */
    constructor($$source: Partial<ProcessInfo> = {}) {
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("ppid" in $$source)) {
            this["ppid"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("cpu_percent" in $$source)) {
            this["cpu_percent"] = 0;
        }
        if (!("memory_bytes" in $$source)) {
            this["memory_bytes"] = 0;
        }
        if (!("rss_bytes" in $$source)) {
            this["rss_bytes"] = 0;
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ProcessInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessInfo($$parsedSource as Partial<ProcessInfo>);
    }
}

export enum RecordType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    RecordStdout = 0,
    RecordStdin = 1,
};

export class RecordingEntry {
    "timestamp": number;
    "type": RecordType;
    "data": string;

    /** Creates a new RecordingEntry instance. */
    constructor($$source: Partial<RecordingEntry> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = 0;
        }
        if (!("type" in $$source)) {
            this["type"] = RecordType.$zero;
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordingEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordingEntry {
        const $$createField2_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new RecordingEntry($$parsedSource as Partial<RecordingEntry>);
    }
}

export class SSHKey {
    "id": number;
    "name": string;
    "type": KeyType;
    "public_key": string;
    "has_passphrase": boolean;
    "created_at": string;

    /** Creates a new SSHKey instance. */
    constructor($$source: Partial<SSHKey> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = KeyType.$zero;
        }
        if (!("public_key" in $$source)) {
            this["public_key"] = "";
        }
        if (!("has_passphrase" in $$source)) {
            this["has_passphrase"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHKey instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHKey {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHKey($$parsedSource as Partial<SSHKey>);
    }
}

export class SSHKeyImportFile {
    "name": string;
    "private_key": string;

    /** Creates a new SSHKeyImportFile instance. */
    constructor($$source: Partial<SSHKeyImportFile> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("private_key" in $$source)) {
            this["private_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHKeyImportFile instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHKeyImportFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHKeyImportFile($$parsedSource as Partial<SSHKeyImportFile>);
    }
}

export class SSHKeyMaterial {
    "id": number;
    "name": string;
    "type": KeyType;
    "private_key": string;
    "public_key": string;
    "created_at": string;

    /** Creates a new SSHKeyMaterial instance. */
    constructor($$source: Partial<SSHKeyMaterial> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = KeyType.$zero;
        }
        if (!("private_key" in $$source)) {
            this["private_key"] = "";
        }
        if (!("public_key" in $$source)) {
            this["public_key"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHKeyMaterial instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHKeyMaterial {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHKeyMaterial($$parsedSource as Partial<SSHKeyMaterial>);
    }
}

export class SSHKeyUpdateInput {
    "id": number;
    "name": string;
    "private_key": string;
    "public_key": string;

    /** Creates a new SSHKeyUpdateInput instance. */
    constructor($$source: Partial<SSHKeyUpdateInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("private_key" in $$source)) {
            this["private_key"] = "";
        }
        if (!("public_key" in $$source)) {
            this["public_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHKeyUpdateInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHKeyUpdateInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHKeyUpdateInput($$parsedSource as Partial<SSHKeyUpdateInput>);
    }
}

export class Session {
    "id": number;
    "folder_id": number | null;
    "name": string;
    "host": string;
    "port": number;
    "username": string;
    "notes": string;
    "environment_id"?: number | null;
    "project_id"?: number | null;
    "environment"?: AssetEnvironment | null;
    "project"?: AssetProject | null;
    "tags": AssetTag[];
    "auth_method": AuthMethod;
    "password"?: string;
    "key_id"?: number | null;
    "keep_alive": number;
    "term_type": string;
    "sort_order": number;
    "last_connected_at"?: string | null;
    "connection_count": number;
    "created_at": string;
    "updated_at": string;

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("folder_id" in $$source)) {
            this["folder_id"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("auth_method" in $$source)) {
            this["auth_method"] = AuthMethod.$zero;
        }
        if (!("keep_alive" in $$source)) {
            this["keep_alive"] = 0;
        }
        if (!("term_type" in $$source)) {
            this["term_type"] = "";
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }
        if (!("connection_count" in $$source)) {
            this["connection_count"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        const $$createField9_0 = $$createType2;
        const $$createField10_0 = $$createType4;
        const $$createField11_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("environment" in $$parsedSource) {
            $$parsedSource["environment"] = $$createField9_0($$parsedSource["environment"]);
        }
        if ("project" in $$parsedSource) {
            $$parsedSource["project"] = $$createField10_0($$parsedSource["project"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField11_0($$parsedSource["tags"]);
        }
        return new Session($$parsedSource as Partial<Session>);
    }
}

export class SessionDeleteImpact {
    "tunnels": number;
    "history": number;
    "recordings": number;

    /** Creates a new SessionDeleteImpact instance. */
    constructor($$source: Partial<SessionDeleteImpact> = {}) {
        if (!("tunnels" in $$source)) {
            this["tunnels"] = 0;
        }
        if (!("history" in $$source)) {
            this["history"] = 0;
        }
        if (!("recordings" in $$source)) {
            this["recordings"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionDeleteImpact instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionDeleteImpact {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionDeleteImpact($$parsedSource as Partial<SessionDeleteImpact>);
    }
}

export class SessionFolder {
    "id": number;
    "name": string;
    "parent_id": number | null;
    "is_default": boolean;
    "sort_order": number;
    "created_at": string;
    "updated_at": string;

    /** Creates a new SessionFolder instance. */
    constructor($$source: Partial<SessionFolder> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("parent_id" in $$source)) {
            this["parent_id"] = null;
        }
        if (!("is_default" in $$source)) {
            this["is_default"] = false;
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionFolder instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionFolder {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionFolder($$parsedSource as Partial<SessionFolder>);
    }
}

export class SessionInput {
    "id": number;
    "folder_id": number | null;
    "name": string;
    "host": string;
    "port": number;
    "username": string;
    "notes": string;
    "environment_id"?: number | null;
    "project_id"?: number | null;
    "tag_ids": number[];
    "auth_method": AuthMethod;
    "password"?: string;
    "key_id"?: number | null;
    "keep_alive": number;
    "term_type": string;
    "sort_order": number;

    /** Creates a new SessionInput instance. */
    constructor($$source: Partial<SessionInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("folder_id" in $$source)) {
            this["folder_id"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("tag_ids" in $$source)) {
            this["tag_ids"] = [];
        }
        if (!("auth_method" in $$source)) {
            this["auth_method"] = AuthMethod.$zero;
        }
        if (!("keep_alive" in $$source)) {
            this["keep_alive"] = 0;
        }
        if (!("term_type" in $$source)) {
            this["term_type"] = "";
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionInput {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tag_ids" in $$parsedSource) {
            $$parsedSource["tag_ids"] = $$createField9_0($$parsedSource["tag_ids"]);
        }
        return new SessionInput($$parsedSource as Partial<SessionInput>);
    }
}

export class SessionLog {
    "id": number;
    "session_id": number | null;
    "started_at": string;
    "ended_at"?: string | null;
    "data_path": string;

    /** Creates a new SessionLog instance. */
    constructor($$source: Partial<SessionLog> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = null;
        }
        if (!("started_at" in $$source)) {
            this["started_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("data_path" in $$source)) {
            this["data_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionLog instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionLog {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionLog($$parsedSource as Partial<SessionLog>);
    }
}

export class Setting {
    "key": string;
    "namespace": string;
    "value": string;
    "value_type": string;
    "version": number;
    "updated_at": string;

    /** Creates a new Setting instance. */
    constructor($$source: Partial<Setting> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("value_type" in $$source)) {
            this["value_type"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Setting instance from a string or object.
     */
    static createFrom($$source: any = {}): Setting {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Setting($$parsedSource as Partial<Setting>);
    }
}

export class SettingInput {
    "key": string;
    "namespace": string;
    "value": string;
    "value_type": string;
    "version": number;

    /** Creates a new SettingInput instance. */
    constructor($$source: Partial<SettingInput> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("value_type" in $$source)) {
            this["value_type"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingInput($$parsedSource as Partial<SettingInput>);
    }
}

export class SystemInfo {
    "cpu_percent": number;
    "cpu_count": number;
    "memory_used": number;
    "memory_total": number;
    "disk_used": number;
    "disk_total": number;
    "download_rate": number;
    "upload_rate": number;
    "swap_used": number;
    "swap_total": number;
    "load_1": number;
    "load_5": number;
    "load_15": number;
    "uptime_seconds": number;
    "os_name": string;
    "kernel_version": string;
    "latency_ms": number;
    "interfaces": NetworkInterface[];

    /** Creates a new SystemInfo instance. */
    constructor($$source: Partial<SystemInfo> = {}) {
        if (!("cpu_percent" in $$source)) {
            this["cpu_percent"] = 0;
        }
        if (!("cpu_count" in $$source)) {
            this["cpu_count"] = 0;
        }
        if (!("memory_used" in $$source)) {
            this["memory_used"] = 0;
        }
        if (!("memory_total" in $$source)) {
            this["memory_total"] = 0;
        }
        if (!("disk_used" in $$source)) {
            this["disk_used"] = 0;
        }
        if (!("disk_total" in $$source)) {
            this["disk_total"] = 0;
        }
        if (!("download_rate" in $$source)) {
            this["download_rate"] = 0;
        }
        if (!("upload_rate" in $$source)) {
            this["upload_rate"] = 0;
        }
        if (!("swap_used" in $$source)) {
            this["swap_used"] = 0;
        }
        if (!("swap_total" in $$source)) {
            this["swap_total"] = 0;
        }
        if (!("load_1" in $$source)) {
            this["load_1"] = 0;
        }
        if (!("load_5" in $$source)) {
            this["load_5"] = 0;
        }
        if (!("load_15" in $$source)) {
            this["load_15"] = 0;
        }
        if (!("uptime_seconds" in $$source)) {
            this["uptime_seconds"] = 0;
        }
        if (!("os_name" in $$source)) {
            this["os_name"] = "";
        }
        if (!("kernel_version" in $$source)) {
            this["kernel_version"] = "";
        }
        if (!("latency_ms" in $$source)) {
            this["latency_ms"] = 0;
        }
        if (!("interfaces" in $$source)) {
            this["interfaces"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SystemInfo {
        const $$createField17_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("interfaces" in $$parsedSource) {
            $$parsedSource["interfaces"] = $$createField17_0($$parsedSource["interfaces"]);
        }
        return new SystemInfo($$parsedSource as Partial<SystemInfo>);
    }
}

export class TerminalGlobalStyle {
    "font_family": string;
    "font_size": number;
    "cursor_style": CursorStyle;
    "selection_background": string;

    /** Creates a new TerminalGlobalStyle instance. */
    constructor($$source: Partial<TerminalGlobalStyle> = {}) {
        if (!("font_family" in $$source)) {
            this["font_family"] = "";
        }
        if (!("font_size" in $$source)) {
            this["font_size"] = 0;
        }
        if (!("cursor_style" in $$source)) {
            this["cursor_style"] = CursorStyle.$zero;
        }
        if (!("selection_background" in $$source)) {
            this["selection_background"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalGlobalStyle instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalGlobalStyle {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalGlobalStyle($$parsedSource as Partial<TerminalGlobalStyle>);
    }
}

export class TerminalGlobalStyleInput {
    "font_family": string;
    "font_size": number;
    "cursor_style": CursorStyle;
    "selection_background": string;

    /** Creates a new TerminalGlobalStyleInput instance. */
    constructor($$source: Partial<TerminalGlobalStyleInput> = {}) {
        if (!("font_family" in $$source)) {
            this["font_family"] = "";
        }
        if (!("font_size" in $$source)) {
            this["font_size"] = 0;
        }
        if (!("cursor_style" in $$source)) {
            this["cursor_style"] = CursorStyle.$zero;
        }
        if (!("selection_background" in $$source)) {
            this["selection_background"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TerminalGlobalStyleInput instance from a string or object.
     */
    static createFrom($$source: any = {}): TerminalGlobalStyleInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TerminalGlobalStyleInput($$parsedSource as Partial<TerminalGlobalStyleInput>);
    }
}

export class ThemeAssignments {
    "dark_profile_id": number;
    "light_profile_id": number;
    "follow_interface_mode": boolean;
    "fixed_profile_id": number;

    /** Creates a new ThemeAssignments instance. */
    constructor($$source: Partial<ThemeAssignments> = {}) {
        if (!("dark_profile_id" in $$source)) {
            this["dark_profile_id"] = 0;
        }
        if (!("light_profile_id" in $$source)) {
            this["light_profile_id"] = 0;
        }
        if (!("follow_interface_mode" in $$source)) {
            this["follow_interface_mode"] = false;
        }
        if (!("fixed_profile_id" in $$source)) {
            this["fixed_profile_id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeAssignments instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeAssignments {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeAssignments($$parsedSource as Partial<ThemeAssignments>);
    }
}

export class ThemeAssignmentsInput {
    "dark_profile_id": number;
    "light_profile_id": number;
    "follow_interface_mode": boolean;
    "fixed_profile_id": number;

    /** Creates a new ThemeAssignmentsInput instance. */
    constructor($$source: Partial<ThemeAssignmentsInput> = {}) {
        if (!("dark_profile_id" in $$source)) {
            this["dark_profile_id"] = 0;
        }
        if (!("light_profile_id" in $$source)) {
            this["light_profile_id"] = 0;
        }
        if (!("follow_interface_mode" in $$source)) {
            this["follow_interface_mode"] = false;
        }
        if (!("fixed_profile_id" in $$source)) {
            this["fixed_profile_id"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeAssignmentsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeAssignmentsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeAssignmentsInput($$parsedSource as Partial<ThemeAssignmentsInput>);
    }
}

export class ThemeConfigurationInput {
    "global_style": TerminalGlobalStyleInput;
    "profiles": ThemeProfileInput[];
    "assignments": ThemeAssignmentsInput;

    /** Creates a new ThemeConfigurationInput instance. */
    constructor($$source: Partial<ThemeConfigurationInput> = {}) {
        if (!("global_style" in $$source)) {
            this["global_style"] = (new TerminalGlobalStyleInput());
        }
        if (!("profiles" in $$source)) {
            this["profiles"] = [];
        }
        if (!("assignments" in $$source)) {
            this["assignments"] = (new ThemeAssignmentsInput());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeConfigurationInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeConfigurationInput {
        const $$createField0_0 = $$createType9;
        const $$createField1_0 = $$createType11;
        const $$createField2_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("global_style" in $$parsedSource) {
            $$parsedSource["global_style"] = $$createField0_0($$parsedSource["global_style"]);
        }
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField1_0($$parsedSource["profiles"]);
        }
        if ("assignments" in $$parsedSource) {
            $$parsedSource["assignments"] = $$createField2_0($$parsedSource["assignments"]);
        }
        return new ThemeConfigurationInput($$parsedSource as Partial<ThemeConfigurationInput>);
    }
}

export class ThemeDefinition {
    "id": number;
    "name": string;
    "mode": ThemeMode;
    "source_type": ThemeSourceType;
    "source_name": string;
    "source_url": string;
    "source_author": string;
    "source_license": string;
    "source_version": string;
    "source_fingerprint": string;
    "color_payload": string;
    "raw_payload": string;
    "is_builtin": boolean;
    "created_at": string;
    "updated_at": string;

    /** Creates a new ThemeDefinition instance. */
    constructor($$source: Partial<ThemeDefinition> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = ThemeMode.$zero;
        }
        if (!("source_type" in $$source)) {
            this["source_type"] = ThemeSourceType.$zero;
        }
        if (!("source_name" in $$source)) {
            this["source_name"] = "";
        }
        if (!("source_url" in $$source)) {
            this["source_url"] = "";
        }
        if (!("source_author" in $$source)) {
            this["source_author"] = "";
        }
        if (!("source_license" in $$source)) {
            this["source_license"] = "";
        }
        if (!("source_version" in $$source)) {
            this["source_version"] = "";
        }
        if (!("source_fingerprint" in $$source)) {
            this["source_fingerprint"] = "";
        }
        if (!("color_payload" in $$source)) {
            this["color_payload"] = "";
        }
        if (!("raw_payload" in $$source)) {
            this["raw_payload"] = "";
        }
        if (!("is_builtin" in $$source)) {
            this["is_builtin"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeDefinition instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeDefinition {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeDefinition($$parsedSource as Partial<ThemeDefinition>);
    }
}

export class ThemeImportResult {
    "file": string;
    "name": string;
    "status": ThemeImportStatus;
    "definition_id": number;
    "profile_id": number;
    "error": string;

    /** Creates a new ThemeImportResult instance. */
    constructor($$source: Partial<ThemeImportResult> = {}) {
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = ThemeImportStatus.$zero;
        }
        if (!("definition_id" in $$source)) {
            this["definition_id"] = 0;
        }
        if (!("profile_id" in $$source)) {
            this["profile_id"] = 0;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeImportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeImportResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeImportResult($$parsedSource as Partial<ThemeImportResult>);
    }
}

export enum ThemeImportStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ThemeImportImported = "imported",
    ThemeImportDuplicate = "duplicate",
    ThemeImportFailed = "failed",
};

export class ThemeImportSummary {
    "results": ThemeImportResult[];

    /** Creates a new ThemeImportSummary instance. */
    constructor($$source: Partial<ThemeImportSummary> = {}) {
        if (!("results" in $$source)) {
            this["results"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeImportSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeImportSummary {
        const $$createField0_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        return new ThemeImportSummary($$parsedSource as Partial<ThemeImportSummary>);
    }
}

export enum ThemeMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ThemeModeDark = "dark",
    ThemeModeLight = "light",
    ThemeModeUniversal = "universal",
};

export class ThemeProfile {
    "id": number;
    "name": string;
    "theme_id": number;
    "definition"?: ThemeDefinition | null;
    "follow_global_style": boolean;
    "font_family": string;
    "font_size": number;
    "cursor_style": CursorStyle;
    "color_overrides": string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new ThemeProfile instance. */
    constructor($$source: Partial<ThemeProfile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("theme_id" in $$source)) {
            this["theme_id"] = 0;
        }
        if (!("follow_global_style" in $$source)) {
            this["follow_global_style"] = false;
        }
        if (!("font_family" in $$source)) {
            this["font_family"] = "";
        }
        if (!("font_size" in $$source)) {
            this["font_size"] = 0;
        }
        if (!("cursor_style" in $$source)) {
            this["cursor_style"] = CursorStyle.$zero;
        }
        if (!("color_overrides" in $$source)) {
            this["color_overrides"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeProfile instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeProfile {
        const $$createField3_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("definition" in $$parsedSource) {
            $$parsedSource["definition"] = $$createField3_0($$parsedSource["definition"]);
        }
        return new ThemeProfile($$parsedSource as Partial<ThemeProfile>);
    }
}

export class ThemeProfileInput {
    "id": number;
    "name": string;
    "theme_id": number;
    "follow_global_style": boolean;
    "font_family": string;
    "font_size": number;
    "cursor_style": CursorStyle;
    "color_overrides": string;

    /** Creates a new ThemeProfileInput instance. */
    constructor($$source: Partial<ThemeProfileInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("theme_id" in $$source)) {
            this["theme_id"] = 0;
        }
        if (!("follow_global_style" in $$source)) {
            this["follow_global_style"] = false;
        }
        if (!("font_family" in $$source)) {
            this["font_family"] = "";
        }
        if (!("font_size" in $$source)) {
            this["font_size"] = 0;
        }
        if (!("cursor_style" in $$source)) {
            this["cursor_style"] = CursorStyle.$zero;
        }
        if (!("color_overrides" in $$source)) {
            this["color_overrides"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeProfileInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ThemeProfileInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ThemeProfileInput($$parsedSource as Partial<ThemeProfileInput>);
    }
}

export enum ThemeSourceType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ThemeSourceBuiltin = "builtin",
    ThemeSourceITerm2 = "iterm2",
    ThemeSourceCommunity = "community",
    ThemeSourceCustom = "custom",
};

export class TransferJob {
    "id": string;
    "session_id": number;
    "session_name": string;
    "direction": string;
    "source_path": string;
    "target_path": string;
    "total_bytes": number;
    "transferred_bytes": number;
    "speed": number;
    "eta": number;
    "status": string;
    "error"?: string;
    "started_at": string;
    "completed_at"?: string | null;

    /** Creates a new TransferJob instance. */
    constructor($$source: Partial<TransferJob> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }
        if (!("session_name" in $$source)) {
            this["session_name"] = "";
        }
        if (!("direction" in $$source)) {
            this["direction"] = "";
        }
        if (!("source_path" in $$source)) {
            this["source_path"] = "";
        }
        if (!("target_path" in $$source)) {
            this["target_path"] = "";
        }
        if (!("total_bytes" in $$source)) {
            this["total_bytes"] = 0;
        }
        if (!("transferred_bytes" in $$source)) {
            this["transferred_bytes"] = 0;
        }
        if (!("speed" in $$source)) {
            this["speed"] = 0;
        }
        if (!("eta" in $$source)) {
            this["eta"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("started_at" in $$source)) {
            this["started_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransferJob instance from a string or object.
     */
    static createFrom($$source: any = {}): TransferJob {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransferJob($$parsedSource as Partial<TransferJob>);
    }
}

export class Tunnel {
    "id": number;
    "session_id": number;
    "name": string;
    "type": TunnelType;
    "local_host"?: string;
    "local_port": number;
    "remote_host"?: string;
    "remote_port": number;
    "created_at": string;

    /** Creates a new Tunnel instance. */
    constructor($$source: Partial<Tunnel> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = TunnelType.$zero;
        }
        if (!("local_port" in $$source)) {
            this["local_port"] = 0;
        }
        if (!("remote_port" in $$source)) {
            this["remote_port"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tunnel instance from a string or object.
     */
    static createFrom($$source: any = {}): Tunnel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tunnel($$parsedSource as Partial<Tunnel>);
    }
}

export class TunnelInput {
    "id": number;
    "session_id": number;
    "name": string;
    "type": TunnelType;
    "local_host"?: string;
    "local_port": number;
    "remote_host"?: string;
    "remote_port": number;

    /** Creates a new TunnelInput instance. */
    constructor($$source: Partial<TunnelInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = TunnelType.$zero;
        }
        if (!("local_port" in $$source)) {
            this["local_port"] = 0;
        }
        if (!("remote_port" in $$source)) {
            this["remote_port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelInput instance from a string or object.
     */
    static createFrom($$source: any = {}): TunnelInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TunnelInput($$parsedSource as Partial<TunnelInput>);
    }
}

export enum TunnelType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TunnelLocal = "local",
    TunnelRemote = "remote",
    TunnelDynamic = "dynamic",
};

export class UpdateInfo {
    "current_version": string;
    "latest_version": string;
    "release_url": string;
    "update_available": boolean;

    /** Creates a new UpdateInfo instance. */
    constructor($$source: Partial<UpdateInfo> = {}) {
        if (!("current_version" in $$source)) {
            this["current_version"] = "";
        }
        if (!("latest_version" in $$source)) {
            this["latest_version"] = "";
        }
        if (!("release_url" in $$source)) {
            this["release_url"] = "";
        }
        if (!("update_available" in $$source)) {
            this["update_available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo($$parsedSource as Partial<UpdateInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = AssetEnvironment.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = AssetProject.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = AssetTag.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = NetworkInterface.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = TerminalGlobalStyleInput.createFrom;
const $$createType10 = ThemeProfileInput.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = ThemeAssignmentsInput.createFrom;
const $$createType13 = ThemeImportResult.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = ThemeDefinition.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
