import type { CSSProperties } from 'react'

export const SESSION_ASSET_HEADER_HEIGHT = 40
export const SESSION_ASSET_VIRTUALIZATION_THRESHOLD = 100
export const SESSION_ASSET_VIRTUAL_OVERSCAN = 8
export const SESSION_ASSET_VIRTUAL_ROW_HEIGHT = 48
export const SESSION_ASSET_VIRTUAL_VIEWPORT_HEIGHT = 576
export const SESSION_ASSET_VIRTUAL_INITIAL_RECT = { width: 0, height: SESSION_ASSET_VIRTUAL_VIEWPORT_HEIGHT }
export const SESSION_ASSET_VIRTUAL_ROW_STYLE: CSSProperties = { height: SESSION_ASSET_VIRTUAL_ROW_HEIGHT }
