// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export class FileEntry {
    "name": string;
    "path": string;
    "size": number;
    "is_dir": boolean;
    "mod_time": string;

    /** Creates a new FileEntry instance. */
    constructor($$source: Partial<FileEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("is_dir" in $$source)) {
            this["is_dir"] = false;
        }
        if (!("mod_time" in $$source)) {
            this["mod_time"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FileEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileEntry($$parsedSource as Partial<FileEntry>);
    }
}

export class Player {
    "cols": number;
    "rows": number;
    "term_type": string;
    "entries": model$0.RecordingEntry[];

    /** Creates a new Player instance. */
    constructor($$source: Partial<Player> = {}) {
        if (!("cols" in $$source)) {
            this["cols"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }
        if (!("term_type" in $$source)) {
            this["term_type"] = "";
        }
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Player instance from a string or object.
     */
    static createFrom($$source: any = {}): Player {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField3_0($$parsedSource["entries"]);
        }
        return new Player($$parsedSource as Partial<Player>);
    }
}

// Private type creation functions
const $$createType0 = model$0.RecordingEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
