// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export function CheckUpdate(): $CancellablePromise<model$0.UpdateInfo | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AboutService.CheckUpdate").then(($result: any) => {
        return $$createType1($result);
    });
}

export function Info(): $CancellablePromise<model$0.AboutInfo> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AboutService.Info").then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.UpdateInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.AboutInfo.createFrom;
