// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export function Chat(request: model$0.AIChatRequest): $CancellablePromise<model$0.AIChatResponse> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.Chat", request).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Dashboard(): $CancellablePromise<model$0.AISettingsDashboard> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.Dashboard").then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteConversation(id: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.DeleteConversation", id);
}

export function DeleteProvider(id: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.DeleteProvider", id);
}

export function DetectAgentCLIs(): $CancellablePromise<model$0.AIAgentCLIStatus[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.DetectAgentCLIs").then(($result: any) => {
        return $$createType3($result);
    });
}

export function ExecuteCommand(input: model$0.AICommandExecutionInput): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.ExecuteCommand", input);
}

export function ListConversations(sessionID: number, limit: number): $CancellablePromise<model$0.AIConversation[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.ListConversations", sessionID, limit).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ListMessages(conversationID: number): $CancellablePromise<model$0.AIMessage[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.ListMessages", conversationID).then(($result: any) => {
        return $$createType7($result);
    });
}

export function SaveProvider(input: model$0.AIProviderProfileInput): $CancellablePromise<model$0.AIProviderProfile | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.SaveProvider", input).then(($result: any) => {
        return $$createType9($result);
    });
}

export function SaveSettings(input: model$0.AISettingsInput): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.SaveSettings", input);
}

export function TestProvider(id: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.TestProvider", id);
}

// Private type creation functions
const $$createType0 = model$0.AIChatResponse.createFrom;
const $$createType1 = model$0.AISettingsDashboard.createFrom;
const $$createType2 = model$0.AIAgentCLIStatus.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = model$0.AIConversation.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = model$0.AIMessage.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = model$0.AIProviderProfile.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
