// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export function ApproveAgentStep(taskID: number, stepID: number, approved: boolean): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.ApproveAgentStep", taskID, stepID, approved);
}

export function CancelAgentTask(taskID: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.CancelAgentTask", taskID);
}

export function Chat(request: model$0.AIChatRequest): $CancellablePromise<model$0.AIChatResponse> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.Chat", request).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Dashboard(): $CancellablePromise<model$0.AISettingsDashboard> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.Dashboard").then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteAgentTask cancels an active execution (when present) and removes the
 * task together with its steps.
 */
export function DeleteAgentTask(taskID: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.DeleteAgentTask", taskID);
}

export function DeleteConversation(id: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.DeleteConversation", id);
}

export function DeleteProvider(id: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.DeleteProvider", id);
}

export function DetectAgentCLIs(): $CancellablePromise<model$0.AIAgentCLIStatus[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.DetectAgentCLIs").then(($result: any) => {
        return $$createType3($result);
    });
}

export function ExecuteCommand(input: model$0.AICommandExecutionInput): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.ExecuteCommand", input);
}

/**
 * GetAgentCLIStatuses returns the last detection snapshot without probing the
 * machine again, so reopening settings still shows the previous result. Call
 * DetectAgentCLIs to refresh it; the refresh writes the new snapshot.
 */
export function GetAgentCLIStatuses(): $CancellablePromise<model$0.AIAgentCLIStatus[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.GetAgentCLIStatuses").then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetAgentMCPServerStatus(): $CancellablePromise<model$0.AIMCPServerStatus> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.GetAgentMCPServerStatus").then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetAgentTask(taskID: number): $CancellablePromise<model$0.AIAgentTask | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.GetAgentTask", taskID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListAgentTasks(sessionID: number, limit: number): $CancellablePromise<model$0.AIAgentTask[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.ListAgentTasks", sessionID, limit).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListConversations(sessionID: number, limit: number): $CancellablePromise<model$0.AIConversation[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.ListConversations", sessionID, limit).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ListMessages(conversationID: number): $CancellablePromise<model$0.AIMessage[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.ListMessages", conversationID).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * ModelsDevCatalog returns models.dev entries compatible with MSSH's provider protocols.
 */
export function ModelsDevCatalog(refresh: boolean): $CancellablePromise<model$0.ModelsDevCatalog> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.ModelsDevCatalog", refresh).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * RegenerateAgentMCPToken rotates the bearer token and restarts a running
 * endpoint so the previous token is rejected immediately.
 */
export function RegenerateAgentMCPToken(): $CancellablePromise<model$0.AIMCPServerStatus> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.RegenerateAgentMCPToken").then(($result: any) => {
        return $$createType4($result);
    });
}

export function ResumeAgentTask(taskID: number): $CancellablePromise<model$0.AIAgentTask | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.ResumeAgentTask", taskID).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * RetryAgentTask creates and starts a new task from a failed task's original
 * execution parameters (session, prompt, engine and CLI).
 */
export function RetryAgentTask(taskID: number): $CancellablePromise<model$0.AIAgentTask | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.RetryAgentTask", taskID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function SaveProvider(input: model$0.AIProviderProfileInput): $CancellablePromise<model$0.AIProviderProfile | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.SaveProvider", input).then(($result: any) => {
        return $$createType14($result);
    });
}

export function SaveSettings(input: model$0.AISettingsInput): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.SaveSettings", input);
}

/**
 * StartAgentMCPServer persists the requested binding and (re)starts the endpoint.
 */
export function StartAgentMCPServer(input: model$0.AIMCPServerInput): $CancellablePromise<model$0.AIMCPServerStatus> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.StartAgentMCPServer", input).then(($result: any) => {
        return $$createType4($result);
    });
}

export function StartAgentTask(input: model$0.AIAgentTaskInput): $CancellablePromise<model$0.AIAgentTask | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.StartAgentTask", input).then(($result: any) => {
        return $$createType6($result);
    });
}

export function StopAgentMCPServer(): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.StopAgentMCPServer");
}

export function TestProvider(id: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AIService.TestProvider", id);
}

// Private type creation functions
const $$createType0 = model$0.AIChatResponse.createFrom;
const $$createType1 = model$0.AISettingsDashboard.createFrom;
const $$createType2 = model$0.AIAgentCLIStatus.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = model$0.AIMCPServerStatus.createFrom;
const $$createType5 = model$0.AIAgentTask.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($$createType5);
const $$createType8 = model$0.AIConversation.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = model$0.AIMessage.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = model$0.ModelsDevCatalog.createFrom;
const $$createType13 = model$0.AIProviderProfile.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
