// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export function BulkSetEnvironment(input: model$0.BulkAssetAssignmentInput): $CancellablePromise<number> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AssetCatalogService.BulkSetEnvironment", input);
}

export function BulkSetProject(input: model$0.BulkAssetAssignmentInput): $CancellablePromise<number> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AssetCatalogService.BulkSetProject", input);
}

export function BulkUpdateTags(input: model$0.BulkTagUpdateInput): $CancellablePromise<number> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AssetCatalogService.BulkUpdateTags", input);
}

export function CreateEnvironment(input: model$0.AssetEnvironmentInput): $CancellablePromise<model$0.AssetEnvironment | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AssetCatalogService.CreateEnvironment", input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateProject(input: model$0.AssetProjectInput): $CancellablePromise<model$0.AssetProject | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AssetCatalogService.CreateProject", input).then(($result: any) => {
        return $$createType3($result);
    });
}

export function CreateTag(input: model$0.AssetTagInput): $CancellablePromise<model$0.AssetTag | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AssetCatalogService.CreateTag", input).then(($result: any) => {
        return $$createType5($result);
    });
}

export function DeleteEnvironment(input: model$0.AssetDeleteInput): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AssetCatalogService.DeleteEnvironment", input);
}

export function DeleteProject(input: model$0.AssetDeleteInput): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AssetCatalogService.DeleteProject", input);
}

export function DeleteTag(id: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AssetCatalogService.DeleteTag", id);
}

export function EnvironmentDeleteImpact(id: number): $CancellablePromise<model$0.AssetDeleteImpact | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AssetCatalogService.EnvironmentDeleteImpact", id).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetSessionAssetDetail(sessionID: number): $CancellablePromise<model$0.Session | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AssetCatalogService.GetSessionAssetDetail", sessionID).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ListEnvironments(): $CancellablePromise<model$0.AssetEnvironment[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AssetCatalogService.ListEnvironments").then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListProjects(): $CancellablePromise<model$0.AssetProject[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AssetCatalogService.ListProjects").then(($result: any) => {
        return $$createType11($result);
    });
}

export function ListTags(): $CancellablePromise<model$0.AssetTag[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AssetCatalogService.ListTags").then(($result: any) => {
        return $$createType12($result);
    });
}

export function ProjectDeleteImpact(id: number): $CancellablePromise<model$0.AssetDeleteImpact | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AssetCatalogService.ProjectDeleteImpact", id).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ReorderEnvironments(ids: number[]): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AssetCatalogService.ReorderEnvironments", ids);
}

export function ReorderProjects(ids: number[]): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AssetCatalogService.ReorderProjects", ids);
}

export function TagDeleteImpact(id: number): $CancellablePromise<model$0.AssetDeleteImpact | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AssetCatalogService.TagDeleteImpact", id).then(($result: any) => {
        return $$createType7($result);
    });
}

export function UpdateEnvironment(input: model$0.AssetEnvironmentInput): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AssetCatalogService.UpdateEnvironment", input);
}

export function UpdateProject(input: model$0.AssetProjectInput): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AssetCatalogService.UpdateProject", input);
}

export function UpdateTag(input: model$0.AssetTagInput): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AssetCatalogService.UpdateTag", input);
}

// Private type creation functions
const $$createType0 = model$0.AssetEnvironment.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.AssetProject.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.AssetTag.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = model$0.AssetDeleteImpact.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = model$0.Session.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $Create.Array($$createType0);
const $$createType11 = $Create.Array($$createType2);
const $$createType12 = $Create.Array($$createType4);
