// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export function Enabled(): $CancellablePromise<boolean> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AuditService.Enabled");
}

export function List(filter: model$0.AuditFilter): $CancellablePromise<model$0.AuditEvent[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AuditService.List", filter).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RecordBatch(action: string, sessionIDs: number[], outcomes: string[]): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AuditService.RecordBatch", action, sessionIDs, outcomes);
}

export function SetEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.AuditService.SetEnabled", enabled);
}

// Private type creation functions
const $$createType0 = model$0.AuditEvent.createFrom;
const $$createType1 = $Create.Array($$createType0);
