// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export function Add(sessionID: number, command: string): $CancellablePromise<model$0.CommandHistory | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.CommandHistoryService.Add", sessionID, command).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Clear(sessionID: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.CommandHistoryService.Clear", sessionID);
}

export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.CommandHistoryService.Delete", id);
}

export function List(sessionID: number, query: string): $CancellablePromise<model$0.CommandHistory[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.CommandHistoryService.List", sessionID, query).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.CommandHistory.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
