// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService manages SFTP file operations with progress tracking.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ssh$0 from "../ssh/models.js";

/**
 * CancelTransfer cancels an in-progress file transfer.
 */
export function CancelTransfer(taskID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.FileService.CancelTransfer", taskID);
}

/**
 * Delete removes a remote file through SFTP.
 */
export function Delete(sessionID: number, path: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.FileService.Delete", sessionID, path);
}

export function Download(sessionID: number, remotePath: string, localPath: string): $CancellablePromise<string> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.FileService.Download", sessionID, remotePath, localPath);
}

export function InstallTerminalDirectoryIntegration(sessionID: number): $CancellablePromise<string[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.FileService.InstallTerminalDirectoryIntegration", sessionID).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListDir lists remote directory entries via SFTP.
 */
export function ListDir(sessionID: number, path: string): $CancellablePromise<ssh$0.FileEntry[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.FileService.ListDir", sessionID, path).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListTransfers(): $CancellablePromise<model$0.TransferJob[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.FileService.ListTransfers").then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Mkdir creates a remote directory through SFTP.
 */
export function Mkdir(sessionID: number, path: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.FileService.Mkdir", sessionID, path);
}

/**
 * Rename renames a remote file through SFTP.
 */
export function Rename(sessionID: number, oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.FileService.Rename", sessionID, oldPath, newPath);
}

export function Upload(sessionID: number, localPath: string, remotePath: string): $CancellablePromise<string> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.FileService.Upload", sessionID, localPath, remotePath);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ssh$0.FileEntry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = model$0.TransferJob.createFrom;
const $$createType4 = $Create.Array($$createType3);
