// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService manages SFTP file operations with progress tracking.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ssh$0 from "../ssh/models.js";

/**
 * CancelTransfer cancels an in-progress file transfer.
 */
export function CancelTransfer(taskID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.FileService.CancelTransfer", taskID);
}

/**
 * Delete removes a remote file via SFTP.
 */
export function Delete(sessionID: number, path: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.FileService.Delete", sessionID, path);
}

/**
 * Download starts an async file download and returns a task ID.
 */
export function Download(sessionID: number, remotePath: string, localPath: string): $CancellablePromise<string> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.FileService.Download", sessionID, remotePath, localPath);
}

/**
 * ListDir lists remote directory entries via SFTP.
 */
export function ListDir(sessionID: number, path: string): $CancellablePromise<ssh$0.FileEntry[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.FileService.ListDir", sessionID, path).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Mkdir creates a remote directory via SFTP.
 */
export function Mkdir(sessionID: number, path: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.FileService.Mkdir", sessionID, path);
}

/**
 * Rename renames a remote file via SFTP.
 */
export function Rename(sessionID: number, oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.FileService.Rename", sessionID, oldPath, newPath);
}

/**
 * Upload starts an async file upload and returns a task ID.
 */
export function Upload(sessionID: number, localPath: string, remotePath: string): $CancellablePromise<string> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.FileService.Upload", sessionID, localPath, remotePath);
}

// Private type creation functions
const $$createType0 = ssh$0.FileEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
