// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export function Create(macro: model$0.Macro): $CancellablePromise<model$0.Macro | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.MacroService.Create", macro).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.MacroService.Delete", id);
}

export function Execute(terminalID: string, command: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.MacroService.Execute", terminalID, command);
}

export function List(): $CancellablePromise<model$0.Macro[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.MacroService.List").then(($result: any) => {
        return $$createType2($result);
    });
}

export function Update(macro: model$0.Macro): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.MacroService.Update", macro);
}

// Private type creation functions
const $$createType0 = model$0.Macro.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
