// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SerialService manages serial port profiles and device discovery.
 */
export class SerialService {

    /** Creates a new SerialService instance. */
    constructor($$source: Partial<SerialService> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SerialService instance from a string or object.
     */
    static createFrom($$source: any = {}): SerialService {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SerialService($$parsedSource as Partial<SerialService>);
    }
}
