// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export function Lock(): $CancellablePromise<model$0.SecurityStatus> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SecurityService.Lock").then(($result: any) => {
        return $$createType0($result);
    });
}

export function Rotate(input: model$0.SecurityRotateInput): $CancellablePromise<model$0.SecurityStatus> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SecurityService.Rotate", input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SavePreferences(input: model$0.SecurityPreferenceInput): $CancellablePromise<model$0.SecurityStatus> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SecurityService.SavePreferences", input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Setup(input: model$0.SecuritySetupInput): $CancellablePromise<model$0.SecurityStatus> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SecurityService.Setup", input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Status(): $CancellablePromise<model$0.SecurityStatus> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SecurityService.Status").then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * TryAutoUnlock restores the DEK from keychain when allowed by preferences.
 */
export function Unlock(input: model$0.SecurityUnlockInput): $CancellablePromise<model$0.SecurityStatus> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SecurityService.Unlock", input).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = model$0.SecurityStatus.createFrom;
