// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SerialService manages serial port profiles and device discovery.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

/**
 * ActiveDeviceMap returns device path -> terminal id for currently open serial sessions.
 */
export function ActiveDeviceMap(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SerialService.ActiveDeviceMap").then(($result: any) => {
        return $$createType0($result);
    });
}

export function Create(input: model$0.SerialPortInput): $CancellablePromise<model$0.SerialPort | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SerialService.Create", input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SerialService.Delete", id);
}

/**
 * DeleteMany removes multiple serial profiles.
 */
export function DeleteMany(ids: number[]): $CancellablePromise<number> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SerialService.DeleteMany", ids);
}

export function Get(id: number): $CancellablePromise<model$0.SerialPort | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SerialService.Get", id).then(($result: any) => {
        return $$createType2($result);
    });
}

export function List(): $CancellablePromise<model$0.SerialPort[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SerialService.List").then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListDevices(): $CancellablePromise<string[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SerialService.ListDevices").then(($result: any) => {
        return $$createType4($result);
    });
}

export function Update(input: model$0.SerialPortInput): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SerialService.Update", input);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = model$0.SerialPort.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType1);
const $$createType4 = $Create.Array($Create.Any);
