// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as ssh$0 from "../ssh/models.js";

export function CancelConnect(attemptID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SessionService.CancelConnect", attemptID);
}

export function Connect(sessionID: number): $CancellablePromise<string> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SessionService.Connect", sessionID);
}

export function ConnectionCount(): $CancellablePromise<number> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SessionService.ConnectionCount");
}

export function CreateFolder(name: string, parentID: number | null): $CancellablePromise<model$0.SessionFolder | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SessionService.CreateFolder", name, parentID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateSession(input: model$0.SessionInput): $CancellablePromise<model$0.Session | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SessionService.CreateSession", input).then(($result: any) => {
        return $$createType3($result);
    });
}

export function DecideHostKey(attemptID: string, accept: boolean): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SessionService.DecideHostKey", attemptID, accept);
}

export function DeleteFolder(id: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SessionService.DeleteFolder", id);
}

export function DeleteSession(id: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SessionService.DeleteSession", id);
}

export function Disconnect(terminalID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SessionService.Disconnect", terminalID);
}

export function GetClientWrapper(connID: string): $CancellablePromise<ssh$0.ClientWrapper | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SessionService.GetClientWrapper", connID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetSession(id: number): $CancellablePromise<model$0.Session | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SessionService.GetSession", id).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListFolders(): $CancellablePromise<model$0.SessionFolder[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SessionService.ListFolders").then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListSessions(folderID: number | null): $CancellablePromise<model$0.Session[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SessionService.ListSessions", folderID).then(($result: any) => {
        return $$createType7($result);
    });
}

export function MoveFolder(id: number, newParentID: number | null): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SessionService.MoveFolder", id, newParentID);
}

export function MoveSession(id: number, newFolderID: number | null): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SessionService.MoveSession", id, newFolderID);
}

export function SetDefaultFolder(id: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SessionService.SetDefaultFolder", id);
}

export function UpdateFolder(id: number, name: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SessionService.UpdateFolder", id, name);
}

export function UpdateSession(input: model$0.SessionInput): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SessionService.UpdateSession", input);
}

// Private type creation functions
const $$createType0 = model$0.SessionFolder.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.Session.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = ssh$0.ClientWrapper.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $Create.Array($$createType0);
const $$createType7 = $Create.Array($$createType2);
