// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function GetSetting(key: string): $CancellablePromise<string> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SettingService.GetSetting", key);
}

export function SetSetting(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SettingService.SetSetting", key, value);
}
