// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Export(path: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SyncService.Export", path);
}

export function Import(path: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SyncService.Import", path);
}

export function SyncFromCloud(endpoint: string, username: string, password: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SyncService.SyncFromCloud", endpoint, username, password);
}

export function SyncToCloud(endpoint: string, username: string, password: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SyncService.SyncToCloud", endpoint, username, password);
}

export function TestCloudConnection(endpoint: string, username: string, password: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.SyncService.TestCloudConnection", endpoint, username, password);
}
