// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Attach(terminalID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.TerminalService.Attach", terminalID);
}

export function Close(terminalID: string): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.TerminalService.Close", terminalID);
}

export function Count(): $CancellablePromise<number> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.TerminalService.Count");
}

export function Open(sessionID: number, cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.TerminalService.Open", sessionID, cols, rows);
}

/**
 * OpenSerial opens a terminal attached to a configured serial port profile.
 */

/**
 * OpenLocal opens a terminal attached to a local interactive shell.
 */
export function OpenLocal(cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.TerminalService.OpenLocal", cols, rows);
}

export function OpenSerial(serialPortID: number, cols: number, rows: number): $CancellablePromise<string> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.TerminalService.OpenSerial", serialPortID, cols, rows);
}

export function ProcessInfo(terminalID: string): $CancellablePromise<model$0.ProcessInfo[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.TerminalService.ProcessInfo", terminalID).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Resize(terminalID: string, cols: number, rows: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.TerminalService.Resize", terminalID, cols, rows);
}


/**
 * SerialBreak sends a break signal on an open serial terminal.
 */
export function SerialBreak(terminalID: string, durationMs: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.TerminalService.SerialBreak", terminalID, durationMs);
}

/**
 * SerialSetSignals updates DTR/RTS for an open serial terminal.
 */
export function SerialSetSignals(terminalID: string, dtr: boolean, rts: boolean): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.TerminalService.SerialSetSignals", terminalID, dtr, rts);
}

/**
 * SerialSignals returns DTR/RTS outputs and modem input status for an open serial terminal.
 */
export function SerialSignals(terminalID: string): $CancellablePromise<model$0.SerialSignals> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.TerminalService.SerialSignals", terminalID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SetCloseHandler(fn: any): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.TerminalService.SetCloseHandler", fn);
}

export function SetMaxSize(maxSize: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.TerminalService.SetMaxSize", maxSize);
}

export function SetOutputHandler(fn: any): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.TerminalService.SetOutputHandler", fn);
}

export function SetSerialService(serialSvc: $models.SerialService | null): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.TerminalService.SetSerialService", serialSvc);
}

export function SystemInfo(terminalID: string): $CancellablePromise<model$0.SystemInfo | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.TerminalService.SystemInfo", terminalID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Write(terminalID: string, data: string): $CancellablePromise<number> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.TerminalService.Write", terminalID, data);
}

// Private type creation functions
const $$createType0 = model$0.ProcessInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = model$0.SystemInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = model$0.SerialSignals.createFrom;
