// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export function CreateCustomProfile(input: model$0.ThemeProfileInput): $CancellablePromise<model$0.ThemeProfile | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.ThemeService.CreateCustomProfile", input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function DeleteDefinition(id: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.ThemeService.DeleteDefinition", id);
}

export function DeleteProfile(id: number): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.ThemeService.DeleteProfile", id);
}

export function GetAssignments(): $CancellablePromise<model$0.ThemeAssignments> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.ThemeService.GetAssignments").then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetGlobalStyle(): $CancellablePromise<model$0.TerminalGlobalStyle> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.ThemeService.GetGlobalStyle").then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetProfile(id: number): $CancellablePromise<model$0.ThemeProfile | null> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.ThemeService.GetProfile", id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function ImportFiles(paths: string[]): $CancellablePromise<model$0.ThemeImportSummary> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.ThemeService.ImportFiles", paths).then(($result: any) => {
        return $$createType4($result);
    });
}

export function InitializeDefaults(): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.ThemeService.InitializeDefaults");
}

export function ListDefinitions(mode: string): $CancellablePromise<model$0.ThemeDefinition[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.ThemeService.ListDefinitions", mode).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListProfiles(mode: string): $CancellablePromise<model$0.ThemeProfile[]> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.ThemeService.ListProfiles", mode).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ResetBuiltinStyles(): $CancellablePromise<model$0.BuiltinThemeResetResult> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.ThemeService.ResetBuiltinStyles").then(($result: any) => {
        return $$createType8($result);
    });
}

export function SaveAssignments(input: model$0.ThemeAssignmentsInput): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.ThemeService.SaveAssignments", input);
}

export function SaveConfiguration(input: model$0.ThemeConfigurationInput): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.ThemeService.SaveConfiguration", input);
}

export function UpdateProfile(input: model$0.ThemeProfileInput): $CancellablePromise<void> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.ThemeService.UpdateProfile", input);
}

// Private type creation functions
const $$createType0 = model$0.ThemeProfile.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = model$0.ThemeAssignments.createFrom;
const $$createType3 = model$0.TerminalGlobalStyle.createFrom;
const $$createType4 = model$0.ThemeImportSummary.createFrom;
const $$createType5 = model$0.ThemeDefinition.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($$createType0);
const $$createType8 = model$0.BuiltinThemeResetResult.createFrom;
