// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export function GetStatus(): $CancellablePromise<model$0.NativeTransparencyStatus> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.WindowAppearanceService.GetStatus").then(($result: any) => {
        return $$createType0($result);
    });
}

export function NativeTransparencyActive(): $CancellablePromise<boolean> {
    return $Call.ByName("github.com/xuthus5/mssh/internal/service.WindowAppearanceService.NativeTransparencyActive");
}

// Private type creation functions
const $$createType0 = model$0.NativeTransparencyStatus.createFrom;
