// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export function Create(tunnel: model$0.Tunnel): $CancellablePromise<model$0.Tunnel | null> {
    return $Call.ByName("mssh/internal/service.TunnelService.Create", tunnel).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByName("mssh/internal/service.TunnelService.Delete", id);
}

export function List(): $CancellablePromise<model$0.Tunnel[]> {
    return $Call.ByName("mssh/internal/service.TunnelService.List").then(($result: any) => {
        return $$createType2($result);
    });
}

export function Start(tunnelID: number): $CancellablePromise<void> {
    return $Call.ByName("mssh/internal/service.TunnelService.Start", tunnelID);
}

export function Stop(tunnelID: number): $CancellablePromise<void> {
    return $Call.ByName("mssh/internal/service.TunnelService.Stop", tunnelID);
}

export function Update(tunnel: model$0.Tunnel): $CancellablePromise<void> {
    return $Call.ByName("mssh/internal/service.TunnelService.Update", tunnel);
}

// Private type creation functions
const $$createType0 = model$0.Tunnel.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
