// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Client implements a traditional SSH client that supports shells,
 * subprocesses, TCP port/streamlocal forwarding and tunneled dialing.
 */
export class Client {
    "Conn": Conn;

    /** Creates a new Client instance. */
    constructor($$source: Partial<Client> = {}) {
        if (!("Conn" in $$source)) {
            this["Conn"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Client instance from a string or object.
     */
    static createFrom($$source: any = {}): Client {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Client($$parsedSource as Partial<Client>);
    }
}

/**
 * Conn represents an SSH connection for both server and client roles.
 * Conn is the basis for implementing an application layer, such
 * as ClientConn, which implements the traditional shell access for
 * clients.
 */
export type Conn = any;
