// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export enum AuthMethod {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AuthPassword = "password",
    AuthKey = "key",
    AuthAgent = "agent",
    AuthKeyboardInteractive = "keyboard-interactive",
};

export enum KeyType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KeyTypeRSA = "rsa",
    KeyTypeED25519 = "ed25519",
    KeyTypeECDSA = "ecdsa",
};

export class Macro {
    "id": number;
    "name": string;
    "command": string;
    "shortcut": string;
    "delay_ms": number;
    "sort_order": number;
    "created_at": string;

    /** Creates a new Macro instance. */
    constructor($$source: Partial<Macro> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("shortcut" in $$source)) {
            this["shortcut"] = "";
        }
        if (!("delay_ms" in $$source)) {
            this["delay_ms"] = 0;
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Macro instance from a string or object.
     */
    static createFrom($$source: any = {}): Macro {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Macro($$parsedSource as Partial<Macro>);
    }
}

export enum RecordType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    RecordStdout = 0,
    RecordStdin = 1,
};

export class RecordingEntry {
    "timestamp": time$0.Duration;
    "type": RecordType;
    "data": string;

    /** Creates a new RecordingEntry instance. */
    constructor($$source: Partial<RecordingEntry> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = time$0.Duration.$zero;
        }
        if (!("type" in $$source)) {
            this["type"] = RecordType.$zero;
        }
        if (!("data" in $$source)) {
            this["data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordingEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordingEntry {
        const $$createField2_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
        }
        return new RecordingEntry($$parsedSource as Partial<RecordingEntry>);
    }
}

export class SSHKey {
    "id": number;
    "name": string;
    "type": KeyType;
    "public_key": string;
    "has_passphrase": boolean;
    "created_at": string;

    /** Creates a new SSHKey instance. */
    constructor($$source: Partial<SSHKey> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = KeyType.$zero;
        }
        if (!("public_key" in $$source)) {
            this["public_key"] = "";
        }
        if (!("has_passphrase" in $$source)) {
            this["has_passphrase"] = false;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSHKey instance from a string or object.
     */
    static createFrom($$source: any = {}): SSHKey {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSHKey($$parsedSource as Partial<SSHKey>);
    }
}

export class Session {
    "id": number;
    "folder_id": number | null;
    "name": string;
    "host": string;
    "port": number;
    "username": string;
    "auth_method": AuthMethod;
    "password"?: string;
    "key_id"?: number | null;
    "keep_alive": number;
    "term_type": string;
    "sort_order": number;
    "created_at": string;
    "updated_at": string;

    /** Creates a new Session instance. */
    constructor($$source: Partial<Session> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("folder_id" in $$source)) {
            this["folder_id"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("auth_method" in $$source)) {
            this["auth_method"] = AuthMethod.$zero;
        }
        if (!("keep_alive" in $$source)) {
            this["keep_alive"] = 0;
        }
        if (!("term_type" in $$source)) {
            this["term_type"] = "";
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     */
    static createFrom($$source: any = {}): Session {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Session($$parsedSource as Partial<Session>);
    }
}

export class SessionFolder {
    "id": number;
    "name": string;
    "parent_id": number | null;
    "sort_order": number;
    "created_at": string;
    "updated_at": string;

    /** Creates a new SessionFolder instance. */
    constructor($$source: Partial<SessionFolder> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("parent_id" in $$source)) {
            this["parent_id"] = null;
        }
        if (!("sort_order" in $$source)) {
            this["sort_order"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionFolder instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionFolder {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionFolder($$parsedSource as Partial<SessionFolder>);
    }
}

export class SessionLog {
    "id": number;
    "session_id": number | null;
    "started_at": string;
    "ended_at"?: string | null;
    "data_path": string;

    /** Creates a new SessionLog instance. */
    constructor($$source: Partial<SessionLog> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = null;
        }
        if (!("started_at" in $$source)) {
            this["started_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("data_path" in $$source)) {
            this["data_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionLog instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionLog {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionLog($$parsedSource as Partial<SessionLog>);
    }
}

export class Theme {
    "id": number;
    "name": string;
    "is_builtin": boolean;
    "config": string;
    "created_at": string;

    /** Creates a new Theme instance. */
    constructor($$source: Partial<Theme> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("is_builtin" in $$source)) {
            this["is_builtin"] = false;
        }
        if (!("config" in $$source)) {
            this["config"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Theme instance from a string or object.
     */
    static createFrom($$source: any = {}): Theme {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Theme($$parsedSource as Partial<Theme>);
    }
}

export class Tunnel {
    "id": number;
    "session_id": number;
    "name": string;
    "type": TunnelType;
    "local_host"?: string;
    "local_port": number;
    "remote_host"?: string;
    "remote_port": number;
    "created_at": string;

    /** Creates a new Tunnel instance. */
    constructor($$source: Partial<Tunnel> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("session_id" in $$source)) {
            this["session_id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = TunnelType.$zero;
        }
        if (!("local_port" in $$source)) {
            this["local_port"] = 0;
        }
        if (!("remote_port" in $$source)) {
            this["remote_port"] = 0;
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tunnel instance from a string or object.
     */
    static createFrom($$source: any = {}): Tunnel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tunnel($$parsedSource as Partial<Tunnel>);
    }
}

export enum TunnelType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TunnelLocal = "local",
    TunnelRemote = "remote",
    TunnelDynamic = "dynamic",
};
