import { useEffect, useMemo, useState } from 'react'
import { Activity, Cpu, HardDrive, MemoryStick, Network, Server, X } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { TerminalService } from '@/lib/wails'

type Info = { cpu_percent:number; cpu_count:number; memory_used:number; memory_total:number; disk_used:number; disk_total:number; download_rate:number; upload_rate:number; swap_used:number; swap_total:number; load_1:number; load_5:number; load_15:number; uptime_seconds:number; os_name:string; kernel_version:string }
type Process = { pid:number; ppid:number; user:string; state:string; cpu_percent:number; memory_bytes:number; command:string }
const bytes = (n:number) => n >= 1024**3 ? `${(n/1024**3).toFixed(1)}G` : `${(n/1024**2).toFixed(1)}M`
const duration = (n:number) => `${Math.floor(n/86400)}d ${Math.floor(n%86400/3600)}h ${Math.floor(n%3600/60)}m`
function Metric({ icon, label, value }:{icon:React.ReactNode;label:string;value:string}) { return <div className="rounded-xl border border-border bg-background/50 p-3"><div className="flex items-center gap-2 text-xs text-muted-foreground">{icon}{label}</div><div className="mt-2 text-sm font-semibold">{value}</div></div> }
export function SystemPanel({ terminalID, onClose }:{terminalID:string;onClose:()=>void}) {
 const [info,setInfo]=useState<Info|null>(null); const [processes,setProcesses]=useState<Process[]>([]); const [failed,setFailed]=useState(false); const [processFailed,setProcessFailed]=useState(false); const [tab,setTab]=useState('overview'); const [query,setQuery]=useState('')
 useEffect(()=>{let cancelled=false; const load=async()=>{try{const value=await TerminalService.SystemInfo(terminalID);if(!cancelled){setInfo(value);setFailed(false)}}catch{if(!cancelled)setFailed(true)}};void load();const timer=setInterval(()=>void load(),3000);return()=>{cancelled=true;clearInterval(timer)}},[terminalID])
 useEffect(()=>{if(tab!=='processes')return;let cancelled=false;const load=async()=>{try{const value=await TerminalService.ProcessInfo(terminalID);if(!cancelled){setProcesses(value);setProcessFailed(false)}}catch{if(!cancelled)setProcessFailed(true)}};void load();const timer=setInterval(()=>void load(),5000);return()=>{cancelled=true;clearInterval(timer)}},[tab,terminalID])
 const filtered=useMemo(()=>processes.filter(p=>`${p.pid} ${p.user} ${p.command}`.toLowerCase().includes(query.toLowerCase())),[processes,query]); const cpuTop=processes.slice().sort((a,b)=>b.cpu_percent-a.cpu_percent).slice(0,5); const memTop=processes.slice().sort((a,b)=>b.memory_bytes-a.memory_bytes).slice(0,5)
 return <aside className="absolute inset-y-0 right-0 z-20 flex w-[min(440px,100%)] flex-col border-l border-border bg-card shadow-xl" data-testid="system-panel"><header className="flex items-center justify-between border-b border-border px-4 py-3"><span className="flex items-center gap-2 text-sm font-semibold"><Server className="size-4"/>系统监控</span><Button size="icon-xs" variant="ghost" aria-label="关闭系统监控" onClick={onClose}><X/></Button></header><Tabs value={tab} onValueChange={setTab} className="flex min-h-0 flex-1 flex-col"><TabsList className="mx-4 mt-3"><TabsTrigger value="overview">概览</TabsTrigger><TabsTrigger value="processes">进程</TabsTrigger></TabsList><TabsContent value="overview" className="min-h-0 flex-1 overflow-y-auto p-4">{failed?<p className="text-sm text-destructive">系统信息采集失败</p>:!info?<p className="text-sm text-muted-foreground">正在采集系统信息...</p>:<div className="space-y-4"><div className="grid grid-cols-2 gap-2"><Metric icon={<Cpu/>} label="CPU" value={`${info.cpu_percent.toFixed(0)}% (${info.cpu_count}c)`}/><Metric icon={<MemoryStick/>} label="内存" value={`${bytes(info.memory_used)}/${bytes(info.memory_total)}`}/><Metric icon={<HardDrive/>} label="磁盘" value={`${bytes(info.disk_used)}/${bytes(info.disk_total)}`}/><Metric icon={<Network/>} label="网络" value={`↓${bytes(info.download_rate)}/s ↑${bytes(info.upload_rate)}/s`}/></div><section className="rounded-xl border border-border p-3 text-xs"><div className="mb-2 font-medium">系统详情</div><div className="grid grid-cols-2 gap-2 text-muted-foreground"><span>负载 {info.load_1.toFixed(2)} / {info.load_5.toFixed(2)} / {info.load_15.toFixed(2)}</span><span>运行 {duration(info.uptime_seconds)}</span><span>系统 {info.os_name||'Linux'}</span><span>内核 {info.kernel_version||'未知'}</span><span>Swap {bytes(info.swap_used)}/{bytes(info.swap_total)}</span></div></section></div>}</TabsContent><TabsContent value="processes" className="min-h-0 flex-1 overflow-y-auto p-4">{processFailed?<p className="text-sm text-destructive">进程信息采集失败</p>:<div className="space-y-3"><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索 PID、用户或命令"/><div className="grid grid-cols-2 gap-3"><Rank title="CPU Top 5" rows={cpuTop} cpu/><Rank title="内存 Top 5" rows={memTop}/></div><div className="overflow-hidden rounded-xl border border-border"><div className="grid grid-cols-[55px_70px_1fr_65px] gap-2 bg-muted/40 px-3 py-2 text-xs text-muted-foreground"><span>PID</span><span>用户</span><span>命令</span><span>资源</span></div>{filtered.map(p=><div key={p.pid} className="grid grid-cols-[55px_70px_1fr_65px] gap-2 border-t border-border px-3 py-2 text-xs"><span>{p.pid}</span><span className="truncate">{p.user}</span><span className="truncate" title={p.command}>{p.command}</span><span>{p.cpu_percent.toFixed(1)}%</span></div>)}</div></div>}</TabsContent></Tabs></aside>
}
function Rank({title,rows,cpu=false}:{title:string;rows:Process[];cpu?:boolean}) { return <div className="rounded-xl border border-border p-3"><div className="mb-2 text-xs font-medium">{title}</div>{rows.map(p=><div key={p.pid} className="flex justify-between gap-2 text-xs text-muted-foreground"><span className="truncate">{p.command}</span><span>{cpu?p.cpu_percent.toFixed(1)+'%':bytes(p.memory_bytes)}</span></div>)}</div> }
